<a href="https://colab.research.google.com/github/irvifa/data-visualization/blob/main/Data_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install datapackage

Collecting datapackage
  Downloading datapackage-1.15.2-py2.py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 2.8 MB/s
Collecting unicodecsv>=0.14
  Downloading unicodecsv-0.14.1.tar.gz (10 kB)
Requirement already satisfied: chardet>=3.0 in /usr/local/lib/python3.7/dist-packages (from datapackage) (3.0.4)
Collecting tabulator>=1.29
  Downloading tabulator-1.53.5-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 535 kB/s
Requirement already satisfied: requests>=2.8 in /usr/local/lib/python3.7/dist-packages (from datapackage) (2.23.0)
Requirement already satisfied: jsonschema>=2.5 in /usr/local/lib/python3.7/dist-packages (from datapackage) (4.3.3)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.7/dist-packages (from datapackage) (7.1.2)
Collecting tableschema>=1.12.1
  Downloading tableschema-1.20.2-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 6.9 MB/s
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from datapackage) (1.15.0)
Collecting jsonpointer>=1.10
  Downloading jsonpointer-2.2-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.5->datapackage) (5.4.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.5->datapackage) (3.10.0.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.5->datapackage) (4.10.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.5->datapackage) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=2.5->datapackage) (21.4.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema>=2.5->datapackage) (3.7.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.8->datapackage) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.8->datapackage) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.8->datapackage) (2.10)
Requirement already satisfied: cached-property>=1.5 in /usr/local/lib/python3.7/dist-packages (from tableschema>=1.12.1->datapackage) (1.5.2)
Collecting isodate>=0.5.4
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 617 kB/s
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from tableschema>=1.12.1->datapackage) (2.8.2)
Collecting rfc3986>=1.1.0
  Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting openpyxl>=2.6
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 36.2 MB/s
Collecting linear-tsv>=1.0
  Downloading linear-tsv-1.1.0.tar.gz (9.6 kB)
Collecting ijson>=3.0.3
  Downloading ijson-3.1.4-cp37-cp37m-manylinux2010_x86_64.whl (126 kB)
     |████████████████████████████████| 126 kB 45.9 MB/s
Requirement already satisfied: sqlalchemy>=0.9.6 in /usr/local/lib/python3.7/dist-packages (from tabulator>=1.29->datapackage) (1.4.31)
Requirement already satisfied: xlrd>=1.0 in /usr/local/lib/python3.7/dist-packages (from tabulator>=1.29->datapackage) (1.1.0)
Collecting jsonlines>=1.1
  Downloading jsonlines-3.0.0-py3-none-any.whl (8.5 kB)
Collecting boto3>=1.9
  Downloading boto3-1.20.48-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 45.7 MB/s
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.1-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 5.9 MB/s
Collecting botocore<1.24.0,>=1.23.48
  Downloading botocore-1.23.48-py3-none-any.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 43.5 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 57.0 MB/s
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl>=2.6->tabulator>=1.29->datapackage) (1.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy>=0.9.6->tabulator>=1.29->datapackage) (1.1.2)
Building wheels for collected packages: linear-tsv, unicodecsv
  Building wheel for linear-tsv (setup.py) ... done
  Created wheel for linear-tsv: filename=linear_tsv-1.1.0-py3-none-any.whl size=7400 sha256=a369146d317856bc45271c0f2357075b61976c3fc72e83035e77ff26e3f71ae3
  Stored in directory: /root/.cache/pip/wheels/dd/0a/62/49ee84fab92057fb3e303fb1a59e75ccac6899b417f441305a
  Building wheel for unicodecsv (setup.py) ... done
  Created wheel for unicodecsv: filename=unicodecsv-0.14.1-py3-none-any.whl size=10768 sha256=28d7ce518df3c05e80afd2f9d1e8770e3d4f64686a3d76736ae5c9752f154d0a
  Stored in directory: /root/.cache/pip/wheels/1a/f4/8a/a5024fb77b32ed369e5c409081e5f00fbe3b92fdad653f6e69
Successfully built linear-tsv unicodecsv
Installing collected packages: urllib3, jmespath, botocore, s3transfer, unicodecsv, openpyxl, linear-tsv, jsonlines, ijson, boto3, tabulator, rfc3986, isodate, tableschema, jsonpointer, datapackage
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: openpyxl
    Found existing installation: openpyxl 2.5.9
    Uninstalling openpyxl-2.5.9:
      Successfully uninstalled openpyxl-2.5.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed boto3-1.20.48 botocore-1.23.48 datapackage-1.15.2 ijson-3.1.4 isodate-0.6.1 jmespath-0.10.0 jsonlines-3.0.0 jsonpointer-2.2 linear-tsv-1.1.0 openpyxl-3.0.9 rfc3986-2.0.0 s3transfer-0.5.1 tableschema-1.20.2 tabulator-1.53.5 unicodecsv-0.14.1 urllib3-1.25.11

In [7]:
from datapackage import Package

package = Package('https://datahub.io/sports-data/italian-serie-a/datapackage.json')
print(package.resource_names)

['validation_report', 'season-1819_csv', 'season-1718_csv', 'season-1617_csv', 'season-1516_csv', 'season-1415_csv', 'season-1314_csv', 'season-1213_csv', 'season-1112_csv', 'season-1011_csv', 'season-0910_csv', 'season-1819_json', 'season-1718_json', 'season-1617_json', 'season-1516_json', 'season-1415_json', 'season-1314_json', 'season-1213_json', 'season-1112_json', 'season-1011_json', 'season-0910_json', 'italian-serie-a_zip', 'season-1819', 'season-1718', 'season-1617', 'season-1516', 'season-1415', 'season-1314', 'season-1213', 'season-1112', 'season-1011', 'season-0910']

In [15]:
seasons_data = [resource.descriptor["name"] for resource in package.resources if resource.descriptor['datahub']['type'] == 'derived/csv']
print(seasons_data)

['season-1819_csv', 'season-1718_csv', 'season-1617_csv', 'season-1516_csv', 'season-1415_csv', 'season-1314_csv', 'season-1213_csv', 'season-1112_csv', 'season-1011_csv', 'season-0910_csv']

In [32]:
from datapackage import Resource
import pandas as pd

for resource in seasons_data:
  df = pd.DataFrame.from_dict(package.get_resource(resource).read(keyed=True))
  df = df.assign(Season=resource.split('_')[0])
  print(resource)
  print(df.columns)
  print(df.head())

season-1819_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA',
       'Season'],
      dtype='object')
  Div        Date HomeTeam  AwayTeam  ...   PSCH  PSCD  PSCA       Season
0  I1  18/08/2018   Chievo  Juventus  ...  18.84  6.42  1.22  season-1819
1  I1  18/08/2018    Lazio    Napoli  ...   2.78  3.57  2.59  season-1819
2  I1  19/08/2018  Bologna      Spal  ...   2.31  3.18  3.59  season-1819
3  I1  19/08/2018   Empoli  Cagliari  ...   2.54  3.42  2.95  season-1819
4  I1  19/08/2018    Parma   Udinese  ...    2.8  3.24  2.78  season-1819

[5 rows x 62 columns]
season-1718_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date  HomeTeam  AwayTeam  ...  PSCH  PSCD  PSCA       Season
0  I1  19/08/17  Juventus  Cagliari  ...  1.13  9.74  27.7  season-1718
1  I1  19/08/17    Verona    Napoli  ...  8.37  5.21  1.41  season-1718
2  I1  20/08/17  Atalanta      Roma  ...  2.99  3.44  2.53  season-1718
3  I1  20/08/17   Bologna    Torino  ...  3.35  3.47  2.31  season-1718
4  I1  20/08/17   Crotone     Milan  ...  7.42  4.37  1.52  season-1718

[5 rows x 65 columns]
season-1617_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date  HomeTeam    AwayTeam  ...  PSCH  PSCD  PSCA       Season
0  I1  20/08/16  Juventus  Fiorentina  ...  1.51  4.15  8.61  season-1617
1  I1  20/08/16      Roma     Udinese  ...  1.46  4.72  8.12  season-1617
2  I1  21/08/16  Atalanta       Lazio  ...  2.96  3.27  2.66  season-1617
3  I1  21/08/16   Bologna     Crotone  ...  1.78   3.5  5.79  season-1617
4  I1  21/08/16    Chievo       Inter  ...  4.14  3.36  2.08  season-1617

[5 rows x 65 columns]
season-1516_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date    HomeTeam AwayTeam  ...  PSCH  PSCD  PSCA       Season
0  I1  22/08/15       Lazio  Bologna  ...  1.48  4.32  8.99  season-1516
1  I1  22/08/15      Verona     Roma  ...  5.68  3.85  1.71  season-1516
2  I1  23/08/15      Empoli   Chievo  ...  2.34  3.31  3.45  season-1516
3  I1  23/08/15  Fiorentina    Milan  ...  2.31  3.35  3.47  season-1516
4  I1  23/08/15   Frosinone   Torino  ...  3.77  3.44  2.16  season-1516

[5 rows x 65 columns]
season-1415_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH',
       'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5',
       'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH',
       'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date  HomeTeam    AwayTeam  ...  PSCH  PSCD  PSCA       Season
0  I1  30/08/14    Chievo    Juventus  ...  8.35  3.84  1.56  season-1415
1  I1  30/08/14      Roma  Fiorentina  ...  1.73   3.8  5.56  season-1415
2  I1  31/08/14  Atalanta      Verona  ...  2.07  3.47  3.99  season-1415
3  I1  31/08/14    Cesena       Parma  ...  5.44  3.65  1.76  season-1415
4  I1  31/08/14     Genoa      Napoli  ...  3.92  3.54  2.07  season-1415

[5 rows x 68 columns]
season-1314_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH',
       'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5',
       'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH',
       'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date   HomeTeam  AwayTeam  ...  PSCH  PSCD  PSCA       Season
0  I1  24/08/13  Sampdoria  Juventus  ...  8.38  4.53  1.47  season-1314
1  I1  24/08/13     Verona     Milan  ...  5.75  3.59  1.76  season-1314
2  I1  25/08/13   Cagliari  Atalanta  ...  2.54  3.22  3.18  season-1314
3  I1  25/08/13      Inter     Genoa  ...  1.65  4.05  5.92  season-1314
4  I1  25/08/13      Lazio   Udinese  ...  1.93  3.48  4.63  season-1314

[5 rows x 68 columns]
season-1213_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH',
       'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD',
       'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA',
       'BSH', 'BSD', 'BSA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA', 'Season'],
      dtype='object')
  Div      Date    HomeTeam  AwayTeam  ...  PSCH  PSCD   PSCA       Season
0  I1  25/08/12  Fiorentina   Udinese  ...  1.97  3.31   4.74  season-1213
1  I1  25/08/12    Juventus     Parma  ...  1.36  5.03  11.65  season-1213
2  I1  26/08/12    Atalanta     Lazio  ...  2.68   3.2   2.98  season-1213
3  I1  26/08/12      Chievo   Bologna  ...  2.04  3.25   4.45  season-1213
4  I1  26/08/12       Genoa  Cagliari  ...  2.64  3.14    3.1  season-1213

[5 rows x 74 columns]
season-1112_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH',
       'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'SBH', 'SBD',
       'SBA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA',
       'BSH', 'BSD', 'BSA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'Season'],
      dtype='object')
  Div      Date    HomeTeam AwayTeam  ...  BbAvAHH  BbMxAHA BbAvAHA       Season
0  I1  09/09/11       Milan    Lazio  ...     2.06     1.86    1.81  season-1112
1  I1  10/09/11      Cesena   Napoli  ...     1.69     2.28    2.21  season-1112
2  I1  11/09/11     Catania    Siena  ...     2.07     1.83    1.78  season-1112
3  I1  11/09/11      Chievo   Novara  ...     1.88     2.01    1.95  season-1112
4  I1  11/09/11  Fiorentina  Bologna  ...     1.83     2.08    2.04  season-1112

[5 rows x 71 columns]
season-1011_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH',
       'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'SBH', 'SBD',
       'SBA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA',
       'BSH', 'BSD', 'BSA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'Season'],
      dtype='object')
  Div      Date    HomeTeam  AwayTeam  ...  BbAvAHH  BbMxAHA BbAvAHA       Season
0  I1  28/08/10        Roma    Cesena  ...     1.86     2.05    2.01  season-1011
1  I1  28/08/10     Udinese     Genoa  ...     1.68     2.23    2.12  season-1011
2  I1  29/08/10        Bari  Juventus  ...     2.72      1.5    1.41  season-1011
3  I1  29/08/10      Chievo   Catania  ...     1.54     2.55     2.4  season-1011
4  I1  29/08/10  Fiorentina    Napoli  ...     1.61     2.43    2.23  season-1011

[5 rows x 71 columns]
season-0910_csv
Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'GBH',
       'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'SBH', 'SBD',
       'SBA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA',
       'BSH', 'BSD', 'BSA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'Season'],
      dtype='object')
  Div        Date HomeTeam    AwayTeam  ...  BbAvAHH  BbMxAHA BbAvAHA       Season
0  I1  2009-08-22  Bologna  Fiorentina  ...     2.38      1.6    1.54  season-0910
1  I1  2009-08-22    Siena       Milan  ...     1.85     2.08    2.02  season-0910
2  I1  2009-08-23  Catania   Sampdoria  ...     1.76     2.12    2.04  season-0910
3  I1  2009-08-23    Genoa        Roma  ...     1.67      2.3    2.13  season-0910
4  I1  2009-08-23    Inter        Bari  ...     1.79     2.15    2.05  season-0910

[5 rows x 71 columns]

In [36]:
combined_csv = pd.concat(pd.DataFrame.from_dict(pd.DataFrame.from_dict(package.get_resource(resource).read(keyed=True))).assign(Season=resource.split('_')[0]) for resource in seasons_data)
combined_csv

    Div        Date   HomeTeam  AwayTeam  FTHG  ...   BSD   BSA   SBH   SBD   SBA
0    I1  18/08/2018     Chievo  Juventus     2  ...   NaN   NaN   NaN   NaN   NaN
1    I1  18/08/2018      Lazio    Napoli     1  ...   NaN   NaN   NaN   NaN   NaN
2    I1  19/08/2018    Bologna      Spal     0  ...   NaN   NaN   NaN   NaN   NaN
3    I1  19/08/2018     Empoli  Cagliari     2  ...   NaN   NaN   NaN   NaN   NaN
4    I1  19/08/2018      Parma   Udinese     2  ...   NaN   NaN   NaN   NaN   NaN
..   ..         ...        ...       ...   ...  ...   ...   ...   ...   ...   ...
375  I1  2010-05-16    Catania     Genoa     1  ...  None  None  None  None  None
376  I1  2010-05-16     Chievo      Roma     0  ...  4.75  1.33   8.5  4.75   1.3
377  I1  2010-05-16      Parma   Livorno     4  ...     4   7.5   1.4   4.2     7
378  I1  2010-05-16  Sampdoria    Napoli     1  ...     5     8  1.29  4.75     9
379  I1  2010-05-16      Siena     Inter     0  ...   7.5  1.12    15     8   1.1

[3800 rows x 77 columns]

In [39]:
combined_csv.to_csv("data.csv", index=False, mode='w+', encoding='utf-8-sig')

In [41]:
print(combined_csv.columns)

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD',
       'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
       'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh',
       'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA',
       'Season', 'LBH', 'LBD', 'LBA', 'SJH', 'SJD', 'SJA', 'GBH', 'GBD', 'GBA',
       'BSH', 'BSD', 'BSA', 'SBH', 'SBD', 'SBA'],
      dtype='object')

In [44]:
filtered_rows = ['Season', 'Date', 'AwayTeam', 'HomeTeam', 'AS', 'HS', 'AST', 'HST', 'HTAG', 'HTHG', 'HTR', 'FTAG', 'FTHG', 'FTR', 'AC', 'HC', 'AF', 'HF', 'AY', 'HY', 'AR', 'HR']

In [50]:
filtered_out_ds = combined_csv[filtered_rows]
filtered_out_ds.head()

        Season        Date  AwayTeam HomeTeam  AS HS AST  ... HC  AF  HF AY  HY  AR HR
0  season-1819  18/08/2018  Juventus   Chievo  23  7  11  ...  0   9   7  0   2   0  0
1  season-1819  18/08/2018    Napoli    Lazio  11  9   6  ...  4   5   8  0   0   0  0
2  season-1819  19/08/2018      Spal  Bologna  10  8   5  ...  7  11  16  2   4   0  1
3  season-1819  19/08/2018  Cagliari   Empoli  12  9   5  ...  6  19  19  3   3   0  0
4  season-1819  19/08/2018   Udinese    Parma  16  9   6  ...  4  13  10  2   2   0  0

[5 rows x 22 columns]

In [51]:
# Half Time Result (H=Home Win, D=Draw, A=Away Win) ║ H=3, D=1, A=0

htr_score_mapping = {"H": 3, "D": 1, "A": 0}
filtered_out_ds['HTR'] = filtered_out_ds['HTR'].map(htr_score_mapping)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [52]:
# Full Time Result (H=Home Win, D=Draw, A=Away Win) ║ H=3, D=1, A=0

ftr_score_mapping = {"H": 3, "D": 1, "A": 0}
filtered_out_ds['FTR'] = filtered_out_ds['FTR'].map(ftr_score_mapping)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [53]:
filtered_out_ds.head()

        Season        Date  AwayTeam HomeTeam  AS HS AST  ... HC  AF  HF  AY  HY  AR  HR
0  season-1819  18/08/2018  Juventus   Chievo  23  7  11  ...  0   9   7   0   2   0   0
1  season-1819  18/08/2018    Napoli    Lazio  11  9   6  ...  4   5   8   0   0   0   0
2  season-1819  19/08/2018      Spal  Bologna  10  8   5  ...  7  11  16   2   4   0   1
3  season-1819  19/08/2018  Cagliari   Empoli  12  9   5  ...  6  19  19   3   3   0   0
4  season-1819  19/08/2018   Udinese    Parma  16  9   6  ...  4  13  10   2   2   0   0

[5 rows x 22 columns]

In [57]:
filtered_out_ds['HomeTeam'].unique()

array(['Chievo', 'Lazio', 'Bologna', 'Empoli', 'Parma', 'Sassuolo',
       'Torino', 'Atalanta', 'Juventus', 'Napoli', 'Cagliari',
       'Fiorentina', 'Frosinone', 'Genoa', 'Inter', 'Spal', 'Udinese',
       'Roma', 'Milan', 'Sampdoria', 'Verona', 'Crotone', 'Benevento',
       'Palermo', 'Pescara', 'Carpi', 'Cesena', 'Livorno', 'Catania',
       'Siena', 'Lecce', 'Novara', 'Bari', 'Brescia'], dtype=object)

In [59]:
len(filtered_out_ds['HomeTeam'].unique())

22